### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Sander-Voogt** [hpolthof/laravel-backblaze#1]
Hello,

I've got this error when I want to install your package.

> Your requirements could not be resolved to an installable set of packages.

**Comment by jacurtis** [comment]
This package (or one of its dependencies) appears to require Laravel 5.3, so in a 5.4 project it will fail during install. I am having the same problem.

**Comment by hpolthof** [comment]
Ok, went for the easiest solution. Just removed the requirement. ;-) You should be able to update with composer.
